In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
data = pd.read_excel(r"C:\Users\Admin\OneDrive\Desktop\Library Resources\Pandas\Pandas Session 1 Resources 16922586003.xlsx")
data

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.00,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.80,248406.36
2,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75
3,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82
4,Sub_Saharan Africa,Rwanda,Office Supplies,Offline,L,2013-06-02,524.96,3296425.02,639077.50
...,...,...,...,...,...,...,...,...,...
95,Sub_Saharan Africa,Mali,Clothes,Online,M,2011-03-09,35.84,97040.64,65214.72
96,Asia,Malaysia,Fruits,Offline,L,2011-12-28,6.92,58471.11,15103.47
97,Sub_Saharan Africa,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,228779.10,93748.05
98,North America,Mexico,Personal Care,Offline,M,2015-08-08,56.67,471336.91,144521.02
99,Sub_Saharan Africa,Mozambique,Household,Offline,L,2012-02-15,502.54,3586605.09,889472.91

In [4]:
data

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.00,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.80,248406.36
2,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75
3,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82
4,Sub_Saharan Africa,Rwanda,Office Supplies,Offline,L,2013-06-02,524.96,3296425.02,639077.50
...,...,...,...,...,...,...,...,...,...
95,Sub_Saharan Africa,Mali,Clothes,Online,M,2011-03-09,35.84,97040.64,65214.72
96,Asia,Malaysia,Fruits,Offline,L,2011-12-28,6.92,58471.11,15103.47
97,Sub_Saharan Africa,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,228779.10,93748.05
98,North America,Mexico,Personal Care,Offline,M,2015-08-08,56.67,471336.91,144521.02
99,Sub_Saharan Africa,Mozambique,Household,Offline,L,2012-02-15,502.54,3586605.09,889472.91

In [5]:
pwd

'C:\\Users\\Admin\\Python_Library_Prac'

In [6]:
print(r"01\08\2025")

01\08\2025

In [7]:
type(data)

pandas.core.frame.DataFrame

In [8]:
data.shape

(100, 9)

In [9]:
data.isnull()

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False

In [10]:
data.isnull().any()

Region            False
Country           False
Item_Type         False
Sales_Channel     False
Order_Priority    False
Ship_Date         False
Unit_Cost         False
Total_Revenue     False
Total_Profit      False
dtype: bool

In [11]:
data.head()

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.00,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.80,248406.36
2,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75
3,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82
4,Sub_Saharan Africa,Rwanda,Office Supplies,Offline,L,2013-06-02,524.96,3296425.02,639077.50

In [12]:
data.head(25)

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.00,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.80,248406.36
2,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75
3,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82
4,Sub_Saharan Africa,Rwanda,Office Supplies,Offline,L,2013-06-02,524.96,3296425.02,639077.50
5,Australia and Oceania,Solomon Islands,Baby Food,Online,C,2015-02-21,159.42,759202.72,285087.64
6,Sub_Saharan Africa,Angola,Household,Offline,M,2011-04-27,502.54,2798046.49,693911.51
7,Sub_Saharan Africa,Burkina Faso,Vegetables,Online,H,2012-07-27,90.93,1245112.92,510216.66
8,Sub_Saharan Africa,Republic of the Congo,Personal Care,Offline,M,2015-08-25,56.67,496101.10,152114.20
9,Sub_Saharan Africa,Senegal,Cereal,Online,H,2014-05-30,117.11,1356180.10,584073.87
10,Asia,Kyrgyzstan,Vegetables,Online,H,2011-12-07,90.93,19103.44,7828.12
11,Sub_Saharan Africa,Cape Verde,Clothes,Offline,H,2014-08-19,35.84,455479.04,306097.92
12,Asia,Bangladesh,Clothes,Online,L,2017-01-03,35.84,902980.64,606834.72
13,Central America and the Caribbean,Honduras,Household,Offline,H,2017-02-13,502.54,5997054.98,1487261.02
14,Asia,Mongolia,Personal Care,Offline,C,2014-02-23,56.67,400558.73,122819.06
15,Europe,Bulgaria,Clothes,Online,M,2012-03-06,35.84,182825.44,122865.12
16,Asia,Sri Lanka,Cosmetics,Offline,M,2016-12-18,263.33,3039414.40,1208744.24
17,Sub_Saharan Africa,Cameroon,Beverages,Offline,C,2015-04-18,31.79,257653.50,85033.80
18,Asia,Turkmenistan,Household,Offline,L,2011-01-20,502.54,2559474.10,634745.90
19,Australia and Oceania,East Timor,Meat,Online,L,2012-11-09,364.69,2492526.12,337937.60
20,Europe,Norway,Baby Food,Online,L,2014-06-28,159.42,1901836.00,714157.00
21,Europe,Portugal,Baby Food,Online,H,2015-03-09,159.42,324971.44,122029.78
22,Central America and the Caribbean,Honduras,Snacks,Online,L,2016-07-26,97.44,339490.50,122686.50
23,Australia and Oceania,New Zealand,Fruits,Online,H,2014-04-10,6.92,20404.71,5270.67
24,Europe,Moldova,Personal Care,Online,L,2016-10-05,56.67,414371.10,127054.20

In [13]:
data.tail()

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
95,Sub_Saharan Africa,Mali,Clothes,Online,M,2011-03-09,35.84,97040.64,65214.72
96,Asia,Malaysia,Fruits,Offline,L,2011-12-28,6.92,58471.11,15103.47
97,Sub_Saharan Africa,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,228779.10,93748.05
98,North America,Mexico,Personal Care,Offline,M,2015-08-08,56.67,471336.91,144521.02
99,Sub_Saharan Africa,Mozambique,Household,Offline,L,2012-02-15,502.54,3586605.09,889472.91

In [14]:
data.tail(7)

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
93,Europe,Romania,Cosmetics,Online,H,2010-12-25,263.33,3458252.00,1375311.70
94,Central America and the Caribbean,Nicaragua,Beverages,Offline,C,2011-03-21,31.79,387002.20,127722.96
95,Sub_Saharan Africa,Mali,Clothes,Online,M,2011-03-09,35.84,97040.64,65214.72
96,Asia,Malaysia,Fruits,Offline,L,2011-12-28,6.92,58471.11,15103.47
97,Sub_Saharan Africa,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,228779.10,93748.05
98,North America,Mexico,Personal Care,Offline,M,2015-08-08,56.67,471336.91,144521.02
99,Sub_Saharan Africa,Mozambique,Household,Offline,L,2012-02-15,502.54,3586605.09,889472.91

In [15]:
data[2:15]

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
2,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75
3,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82
4,Sub_Saharan Africa,Rwanda,Office Supplies,Offline,L,2013-06-02,524.96,3296425.02,639077.50
5,Australia and Oceania,Solomon Islands,Baby Food,Online,C,2015-02-21,159.42,759202.72,285087.64
6,Sub_Saharan Africa,Angola,Household,Offline,M,2011-04-27,502.54,2798046.49,693911.51
7,Sub_Saharan Africa,Burkina Faso,Vegetables,Online,H,2012-07-27,90.93,1245112.92,510216.66
8,Sub_Saharan Africa,Republic of the Congo,Personal Care,Offline,M,2015-08-25,56.67,496101.10,152114.20
9,Sub_Saharan Africa,Senegal,Cereal,Online,H,2014-05-30,117.11,1356180.10,584073.87
10,Asia,Kyrgyzstan,Vegetables,Online,H,2011-12-07,90.93,19103.44,7828.12
11,Sub_Saharan Africa,Cape Verde,Clothes,Offline,H,2014-08-19,35.84,455479.04,306097.92
12,Asia,Bangladesh,Clothes,Online,L,2017-01-03,35.84,902980.64,606834.72
13,Central America and the Caribbean,Honduras,Household,Offline,H,2017-02-13,502.54,5997054.98,1487261.02
14,Asia,Mongolia,Personal Care,Offline,C,2014-02-23,56.67,400558.73,122819.06

In [16]:
data[2:25:3]

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
2,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75
5,Australia and Oceania,Solomon Islands,Baby Food,Online,C,2015-02-21,159.42,759202.72,285087.64
8,Sub_Saharan Africa,Republic of the Congo,Personal Care,Offline,M,2015-08-25,56.67,496101.10,152114.20
11,Sub_Saharan Africa,Cape Verde,Clothes,Offline,H,2014-08-19,35.84,455479.04,306097.92
14,Asia,Mongolia,Personal Care,Offline,C,2014-02-23,56.67,400558.73,122819.06
17,Sub_Saharan Africa,Cameroon,Beverages,Offline,C,2015-04-18,31.79,257653.50,85033.80
20,Europe,Norway,Baby Food,Online,L,2014-06-28,159.42,1901836.00,714157.00
23,Australia and Oceania,New Zealand,Fruits,Online,H,2014-04-10,6.92,20404.71,5270.67

In [17]:
a = {"":"","":"","":""}

In [18]:
type(data["Region"])

pandas.core.series.Series

In [19]:
data[["Region","Country"]][2:15]

                               Region                Country
2                              Europe                 Russia
3                  Sub_Saharan Africa  Sao Tome and Principe
4                  Sub_Saharan Africa                 Rwanda
5               Australia and Oceania        Solomon Islands
6                  Sub_Saharan Africa                 Angola
7                  Sub_Saharan Africa           Burkina Faso
8                  Sub_Saharan Africa  Republic of the Congo
9                  Sub_Saharan Africa                Senegal
10                               Asia             Kyrgyzstan
11                 Sub_Saharan Africa             Cape Verde
12                               Asia             Bangladesh
13  Central America and the Caribbean               Honduras
14                               Asia               Mongolia

In [20]:
data.loc[5,"Region"]

'Australia and Oceania'

In [21]:
data.loc[[1,41,54,34,84],["Region","Country"]]

                               Region                Country
1   Central America and the Caribbean                Grenada
41       Middle East and North Africa             Azerbaijan
54                 Sub_Saharan Africa  Sao Tome and Principe
34                 Sub_Saharan Africa               Djibouti
84                 Sub_Saharan Africa                  Kenya

In [22]:
data["Region"]

0                 Australia and Oceania
1     Central America and the Caribbean
2                                Europe
3                    Sub_Saharan Africa
4                    Sub_Saharan Africa
                    ...
95                   Sub_Saharan Africa
96                                 Asia
97                   Sub_Saharan Africa
98                        North America
99                   Sub_Saharan Africa
Name: Region, Length: 100, dtype: object

In [23]:
data.loc[41,["Region","Country","Item_Type","Sales_Channel"]]

Region           Middle East and North Africa
Country                            Azerbaijan
Item_Type                           Cosmetics
Sales_Channel                          Online
Name: 41, dtype: object

In [24]:
data.iloc[54,[0,1,2,3]]

Region              Sub_Saharan Africa
Country          Sao Tome and Principe
Item_Type                       Fruits
Sales_Channel                  Offline
Name: 54, dtype: object

In [25]:
data.loc[2,"Sales_Channel"] = "Online"

In [26]:
data.head()

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.00,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.80,248406.36
2,Europe,Russia,Office Supplies,Online,L,2014-08-05,524.96,1158502.59,224598.75
3,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82
4,Sub_Saharan Africa,Rwanda,Office Supplies,Offline,L,2013-06-02,524.96,3296425.02,639077.50

In [27]:
data.iloc[2,3] = "Offline"

In [28]:
data.head()

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.00,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.80,248406.36
2,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75
3,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82
4,Sub_Saharan Africa,Rwanda,Office Supplies,Offline,L,2013-06-02,524.96,3296425.02,639077.50

In [29]:
data1 = data.copy()

In [30]:
data.loc[4,["Region","Country","Item_Type","Sales_Channel"]] = "Y" , "A" , "S" ,"H"

In [31]:
data.head()

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.00,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.80,248406.36
2,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75
3,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82
4,Y,A,S,H,L,2013-06-02,524.96,3296425.02,639077.50

In [32]:
data.loc[7,["Region","Country","Sales_Channel"]] = ["Asia","India","Offline"]

In [33]:
data.loc[[7]]

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
7,Asia,India,Vegetables,Offline,H,2012-07-27,90.93,1245112.92,510216.66

In [34]:
data["add"] = data["Region"] + " "+ data["Order_Priority"]

In [35]:
data

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit,add
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.00,951410.50,Australia and Oceania H
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.80,248406.36,Central America and the Caribbean C
2,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75,Europe L
3,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82,Sub_Saharan Africa C
4,Y,A,S,H,L,2013-06-02,524.96,3296425.02,639077.50,Y L
...,...,...,...,...,...,...,...,...,...,...
95,Sub_Saharan Africa,Mali,Clothes,Online,M,2011-03-09,35.84,97040.64,65214.72,Sub_Saharan Africa M
96,Asia,Malaysia,Fruits,Offline,L,2011-12-28,6.92,58471.11,15103.47,Asia L
97,Sub_Saharan Africa,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,228779.10,93748.05,Sub_Saharan Africa C
98,North America,Mexico,Personal Care,Offline,M,2015-08-08,56.67,471336.91,144521.02,North America M
99,Sub_Saharan Africa,Mozambique,Household,Offline,L,2012-02-15,502.54,3586605.09,889472.91,Sub_Saharan Africa L

In [36]:
data["sum"] = data["Unit_Cost"] + data["Total_Revenue"]

In [37]:
data

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit,add,sum
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.00,951410.50,Australia and Oceania H,2533813.42
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.80,248406.36,Central America and the Caribbean C,576899.91
2,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75,Europe L,1159027.55
3,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82,Sub_Saharan Africa C,75598.58
4,Y,A,S,H,L,2013-06-02,524.96,3296425.02,639077.50,Y L,3296949.98
...,...,...,...,...,...,...,...,...,...,...,...
95,Sub_Saharan Africa,Mali,Clothes,Online,M,2011-03-09,35.84,97040.64,65214.72,Sub_Saharan Africa M,97076.48
96,Asia,Malaysia,Fruits,Offline,L,2011-12-28,6.92,58471.11,15103.47,Asia L,58478.03
97,Sub_Saharan Africa,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,228779.10,93748.05,Sub_Saharan Africa C,228870.03
98,North America,Mexico,Personal Care,Offline,M,2015-08-08,56.67,471336.91,144521.02,North America M,471393.58
99,Sub_Saharan Africa,Mozambique,Household,Offline,L,2012-02-15,502.54,3586605.09,889472.91,Sub_Saharan Africa L,3587107.63

In [38]:
data["new_unitcost"] = data["Unit_Cost"] / 2

In [39]:
data

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit,add,sum,new_unitcost
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.00,951410.50,Australia and Oceania H,2533813.42,79.710
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.80,248406.36,Central America and the Caribbean C,576899.91,58.555
2,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75,Europe L,1159027.55,262.480
3,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82,Sub_Saharan Africa C,75598.58,3.460
4,Y,A,S,H,L,2013-06-02,524.96,3296425.02,639077.50,Y L,3296949.98,262.480
...,...,...,...,...,...,...,...,...,...,...,...,...
95,Sub_Saharan Africa,Mali,Clothes,Online,M,2011-03-09,35.84,97040.64,65214.72,Sub_Saharan Africa M,97076.48,17.920
96,Asia,Malaysia,Fruits,Offline,L,2011-12-28,6.92,58471.11,15103.47,Asia L,58478.03,3.460
97,Sub_Saharan Africa,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,228779.10,93748.05,Sub_Saharan Africa C,228870.03,45.465
98,North America,Mexico,Personal Care,Offline,M,2015-08-08,56.67,471336.91,144521.02,North America M,471393.58,28.335
99,Sub_Saharan Africa,Mozambique,Household,Offline,L,2012-02-15,502.54,3586605.09,889472.91,Sub_Saharan Africa L,3587107.63,251.270

In [40]:
data["new"] = range(100)

In [41]:
data

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit,add,sum,new_unitcost,new
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.00,951410.50,Australia and Oceania H,2533813.42,79.710,0
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.80,248406.36,Central America and the Caribbean C,576899.91,58.555,1
2,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75,Europe L,1159027.55,262.480,2
3,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82,Sub_Saharan Africa C,75598.58,3.460,3
4,Y,A,S,H,L,2013-06-02,524.96,3296425.02,639077.50,Y L,3296949.98,262.480,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Sub_Saharan Africa,Mali,Clothes,Online,M,2011-03-09,35.84,97040.64,65214.72,Sub_Saharan Africa M,97076.48,17.920,95
96,Asia,Malaysia,Fruits,Offline,L,2011-12-28,6.92,58471.11,15103.47,Asia L,58478.03,3.460,96
97,Sub_Saharan Africa,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,228779.10,93748.05,Sub_Saharan Africa C,228870.03,45.465,97
98,North America,Mexico,Personal Care,Offline,M,2015-08-08,56.67,471336.91,144521.02,North America M,471393.58,28.335,98
99,Sub_Saharan Africa,Mozambique,Household,Offline,L,2012-02-15,502.54,3586605.09,889472.91,Sub_Saharan Africa L,3587107.63,251.270,99

In [42]:
data.columns

Index(['Region', 'Country', 'Item_Type', 'Sales_Channel', 'Order_Priority',
       'Ship_Date', 'Unit_Cost', 'Total_Revenue', 'Total_Profit', 'add', 'sum',
       'new_unitcost', 'new'],
      dtype='object')

In [43]:
data = data[['Total_Revenue', 'Total_Profit', 'add', 'sum','Region', 'Country', 'Item_Type', 'Sales_Channel', 'Order_Priority',
       'Ship_Date', 'Unit_Cost', 
       'new_unitcost', 'new']]

In [44]:
data

,Total_Revenue,Total_Profit,add,sum,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,new_unitcost,new
0,2533654.00,951410.50,Australia and Oceania H,2533813.42,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,79.710,0
1,576782.80,248406.36,Central America and the Caribbean C,576899.91,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,58.555,1
2,1158502.59,224598.75,Europe L,1159027.55,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,262.480,2
3,75591.66,19525.82,Sub_Saharan Africa C,75598.58,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,3.460,3
4,3296425.02,639077.50,Y L,3296949.98,Y,A,S,H,L,2013-06-02,524.96,262.480,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,97040.64,65214.72,Sub_Saharan Africa M,97076.48,Sub_Saharan Africa,Mali,Clothes,Online,M,2011-03-09,35.84,17.920,95
96,58471.11,15103.47,Asia L,58478.03,Asia,Malaysia,Fruits,Offline,L,2011-12-28,6.92,3.460,96
97,228779.10,93748.05,Sub_Saharan Africa C,228870.03,Sub_Saharan Africa,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,45.465,97
98,471336.91,144521.02,North America M,471393.58,North America,Mexico,Personal Care,Offline,M,2015-08-08,56.67,28.335,98
99,3586605.09,889472.91,Sub_Saharan Africa L,3587107.63,Sub_Saharan Africa,Mozambique,Household,Offline,L,2012-02-15,502.54,251.270,99

In [45]:
a = {
    "Region":"a",
    "Country":"b",
    "Item_Type":"c"
}

In [46]:
data.rename(columns=a)

,Total_Revenue,Total_Profit,add,sum,a,b,c,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,new_unitcost,new
0,2533654.00,951410.50,Australia and Oceania H,2533813.42,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,79.710,0
1,576782.80,248406.36,Central America and the Caribbean C,576899.91,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,58.555,1
2,1158502.59,224598.75,Europe L,1159027.55,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,262.480,2
3,75591.66,19525.82,Sub_Saharan Africa C,75598.58,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,3.460,3
4,3296425.02,639077.50,Y L,3296949.98,Y,A,S,H,L,2013-06-02,524.96,262.480,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,97040.64,65214.72,Sub_Saharan Africa M,97076.48,Sub_Saharan Africa,Mali,Clothes,Online,M,2011-03-09,35.84,17.920,95
96,58471.11,15103.47,Asia L,58478.03,Asia,Malaysia,Fruits,Offline,L,2011-12-28,6.92,3.460,96
97,228779.10,93748.05,Sub_Saharan Africa C,228870.03,Sub_Saharan Africa,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,45.465,97
98,471336.91,144521.02,North America M,471393.58,North America,Mexico,Personal Care,Offline,M,2015-08-08,56.67,28.335,98
99,3586605.09,889472.91,Sub_Saharan Africa L,3587107.63,Sub_Saharan Africa,Mozambique,Household,Offline,L,2012-02-15,502.54,251.270,99

In [47]:
data.loc[2:10,"Region":"new"]

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,new_unitcost,new
2,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,262.480,2
3,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,3.460,3
4,Y,A,S,H,L,2013-06-02,524.96,262.480,4
5,Australia and Oceania,Solomon Islands,Baby Food,Online,C,2015-02-21,159.42,79.710,5
6,Sub_Saharan Africa,Angola,Household,Offline,M,2011-04-27,502.54,251.270,6
7,Asia,India,Vegetables,Offline,H,2012-07-27,90.93,45.465,7
8,Sub_Saharan Africa,Republic of the Congo,Personal Care,Offline,M,2015-08-25,56.67,28.335,8
9,Sub_Saharan Africa,Senegal,Cereal,Online,H,2014-05-30,117.11,58.555,9
10,Asia,Kyrgyzstan,Vegetables,Online,H,2011-12-07,90.93,45.465,10

In [48]:
data.iloc[2:10,4:12]

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,new_unitcost
2,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,262.480
3,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,3.460
4,Y,A,S,H,L,2013-06-02,524.96,262.480
5,Australia and Oceania,Solomon Islands,Baby Food,Online,C,2015-02-21,159.42,79.710
6,Sub_Saharan Africa,Angola,Household,Offline,M,2011-04-27,502.54,251.270
7,Asia,India,Vegetables,Offline,H,2012-07-27,90.93,45.465
8,Sub_Saharan Africa,Republic of the Congo,Personal Care,Offline,M,2015-08-25,56.67,28.335
9,Sub_Saharan Africa,Senegal,Cereal,Online,H,2014-05-30,117.11,58.555

In [49]:
string = "yash shah is the great"

In [50]:
string[0:10:2]

'ys hh'

In [51]:
string[3:-6]

'h shah is the'

In [52]:
data

,Total_Revenue,Total_Profit,add,sum,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,new_unitcost,new
0,2533654.00,951410.50,Australia and Oceania H,2533813.42,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,79.710,0
1,576782.80,248406.36,Central America and the Caribbean C,576899.91,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,58.555,1
2,1158502.59,224598.75,Europe L,1159027.55,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,262.480,2
3,75591.66,19525.82,Sub_Saharan Africa C,75598.58,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,3.460,3
4,3296425.02,639077.50,Y L,3296949.98,Y,A,S,H,L,2013-06-02,524.96,262.480,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,97040.64,65214.72,Sub_Saharan Africa M,97076.48,Sub_Saharan Africa,Mali,Clothes,Online,M,2011-03-09,35.84,17.920,95
96,58471.11,15103.47,Asia L,58478.03,Asia,Malaysia,Fruits,Offline,L,2011-12-28,6.92,3.460,96
97,228779.10,93748.05,Sub_Saharan Africa C,228870.03,Sub_Saharan Africa,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,45.465,97
98,471336.91,144521.02,North America M,471393.58,North America,Mexico,Personal Care,Offline,M,2015-08-08,56.67,28.335,98
99,3586605.09,889472.91,Sub_Saharan Africa L,3587107.63,Sub_Saharan Africa,Mozambique,Household,Offline,L,2012-02-15,502.54,251.270,99