In [1]:
import pandas as pd

In [2]:
data = pd.read_excel(r"C:\Users\Admin\OneDrive\Desktop\Library Resources\Pandas\Pandas Session 1 Resources 16922586003.xlsx")
data

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.00,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.80,248406.36
2,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75
3,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82
4,Sub_Saharan Africa,Rwanda,Office Supplies,Offline,L,2013-06-02,524.96,3296425.02,639077.50
...,...,...,...,...,...,...,...,...,...
95,Sub_Saharan Africa,Mali,Clothes,Online,M,2011-03-09,35.84,97040.64,65214.72
96,Asia,Malaysia,Fruits,Offline,L,2011-12-28,6.92,58471.11,15103.47
97,Sub_Saharan Africa,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,228779.10,93748.05
98,North America,Mexico,Personal Care,Offline,M,2015-08-08,56.67,471336.91,144521.02
99,Sub_Saharan Africa,Mozambique,Household,Offline,L,2012-02-15,502.54,3586605.09,889472.91

In [3]:
data1 = data.copy()

In [4]:
data.drop("Region",axis=1)

,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
0,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.00,951410.50
1,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.80,248406.36
2,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75
3,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82
4,Rwanda,Office Supplies,Offline,L,2013-06-02,524.96,3296425.02,639077.50
...,...,...,...,...,...,...,...,...
95,Mali,Clothes,Online,M,2011-03-09,35.84,97040.64,65214.72
96,Malaysia,Fruits,Offline,L,2011-12-28,6.92,58471.11,15103.47
97,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,228779.10,93748.05
98,Mexico,Personal Care,Offline,M,2015-08-08,56.67,471336.91,144521.02
99,Mozambique,Household,Offline,L,2012-02-15,502.54,3586605.09,889472.91

In [5]:
data.head(2)

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.0,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.8,248406.36

In [6]:
data.drop("Region",axis=1,inplace=True)

In [7]:
data

,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
0,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.00,951410.50
1,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.80,248406.36
2,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75
3,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82
4,Rwanda,Office Supplies,Offline,L,2013-06-02,524.96,3296425.02,639077.50
...,...,...,...,...,...,...,...,...
95,Mali,Clothes,Online,M,2011-03-09,35.84,97040.64,65214.72
96,Malaysia,Fruits,Offline,L,2011-12-28,6.92,58471.11,15103.47
97,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,228779.10,93748.05
98,Mexico,Personal Care,Offline,M,2015-08-08,56.67,471336.91,144521.02
99,Mozambique,Household,Offline,L,2012-02-15,502.54,3586605.09,889472.91

In [8]:
data.drop([0,1,2])

,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
3,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82
4,Rwanda,Office Supplies,Offline,L,2013-06-02,524.96,3296425.02,639077.50
5,Solomon Islands,Baby Food,Online,C,2015-02-21,159.42,759202.72,285087.64
6,Angola,Household,Offline,M,2011-04-27,502.54,2798046.49,693911.51
7,Burkina Faso,Vegetables,Online,H,2012-07-27,90.93,1245112.92,510216.66
...,...,...,...,...,...,...,...,...
95,Mali,Clothes,Online,M,2011-03-09,35.84,97040.64,65214.72
96,Malaysia,Fruits,Offline,L,2011-12-28,6.92,58471.11,15103.47
97,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,228779.10,93748.05
98,Mexico,Personal Care,Offline,M,2015-08-08,56.67,471336.91,144521.02
99,Mozambique,Household,Offline,L,2012-02-15,502.54,3586605.09,889472.91

In [9]:
data.drop(0,inplace=True)

In [10]:
data

,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
1,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.80,248406.36
2,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75
3,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82
4,Rwanda,Office Supplies,Offline,L,2013-06-02,524.96,3296425.02,639077.50
5,Solomon Islands,Baby Food,Online,C,2015-02-21,159.42,759202.72,285087.64
...,...,...,...,...,...,...,...,...
95,Mali,Clothes,Online,M,2011-03-09,35.84,97040.64,65214.72
96,Malaysia,Fruits,Offline,L,2011-12-28,6.92,58471.11,15103.47
97,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,228779.10,93748.05
98,Mexico,Personal Care,Offline,M,2015-08-08,56.67,471336.91,144521.02
99,Mozambique,Household,Offline,L,2012-02-15,502.54,3586605.09,889472.91

In [11]:
for i in range(1,5):
    data.drop(i,inplace=True)

In [12]:
data

,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
5,Solomon Islands,Baby Food,Online,C,2015-02-21,159.42,759202.72,285087.64
6,Angola,Household,Offline,M,2011-04-27,502.54,2798046.49,693911.51
7,Burkina Faso,Vegetables,Online,H,2012-07-27,90.93,1245112.92,510216.66
8,Republic of the Congo,Personal Care,Offline,M,2015-08-25,56.67,496101.10,152114.20
9,Senegal,Cereal,Online,H,2014-05-30,117.11,1356180.10,584073.87
...,...,...,...,...,...,...,...,...
95,Mali,Clothes,Online,M,2011-03-09,35.84,97040.64,65214.72
96,Malaysia,Fruits,Offline,L,2011-12-28,6.92,58471.11,15103.47
97,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,228779.10,93748.05
98,Mexico,Personal Care,Offline,M,2015-08-08,56.67,471336.91,144521.02
99,Mozambique,Household,Offline,L,2012-02-15,502.54,3586605.09,889472.91

In [13]:
data.iloc[[5,6,7,8],[0,1,2]]

       Country   Item_Type Sales_Channel
10  Kyrgyzstan  Vegetables        Online
11  Cape Verde     Clothes       Offline
12  Bangladesh     Clothes        Online
13    Honduras   Household       Offline

In [14]:
data

,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
5,Solomon Islands,Baby Food,Online,C,2015-02-21,159.42,759202.72,285087.64
6,Angola,Household,Offline,M,2011-04-27,502.54,2798046.49,693911.51
7,Burkina Faso,Vegetables,Online,H,2012-07-27,90.93,1245112.92,510216.66
8,Republic of the Congo,Personal Care,Offline,M,2015-08-25,56.67,496101.10,152114.20
9,Senegal,Cereal,Online,H,2014-05-30,117.11,1356180.10,584073.87
...,...,...,...,...,...,...,...,...
95,Mali,Clothes,Online,M,2011-03-09,35.84,97040.64,65214.72
96,Malaysia,Fruits,Offline,L,2011-12-28,6.92,58471.11,15103.47
97,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,228779.10,93748.05
98,Mexico,Personal Care,Offline,M,2015-08-08,56.67,471336.91,144521.02
99,Mozambique,Household,Offline,L,2012-02-15,502.54,3586605.09,889472.91

In [15]:
data.drop(["Country","Item_Type","Sales_Channel"],axis=1,inplace=True)

In [16]:
data

   Order_Priority  Ship_Date  Unit_Cost  Total_Revenue  Total_Profit
5               C 2015-02-21     159.42      759202.72     285087.64
6               M 2011-04-27     502.54     2798046.49     693911.51
7               H 2012-07-27      90.93     1245112.92     510216.66
8               M 2015-08-25      56.67      496101.10     152114.20
9               H 2014-05-30     117.11     1356180.10     584073.87
..            ...        ...        ...            ...           ...
95              M 2011-03-09      35.84       97040.64      65214.72
96              L 2011-12-28       6.92       58471.11      15103.47
97              C 2016-06-29      90.93      228779.10      93748.05
98              M 2015-08-08      56.67      471336.91     144521.02
99              L 2012-02-15     502.54     3586605.09     889472.91

[95 rows x 5 columns]

In [17]:
data.drop([5,7,9],inplace=True)

In [18]:
data

   Order_Priority  Ship_Date  Unit_Cost  Total_Revenue  Total_Profit
6               M 2011-04-27     502.54     2798046.49     693911.51
8               M 2015-08-25      56.67      496101.10     152114.20
10              H 2011-12-07      90.93       19103.44       7828.12
11              H 2014-08-19      35.84      455479.04     306097.92
12              L 2017-01-03      35.84      902980.64     606834.72
..            ...        ...        ...            ...           ...
95              M 2011-03-09      35.84       97040.64      65214.72
96              L 2011-12-28       6.92       58471.11      15103.47
97              C 2016-06-29      90.93      228779.10      93748.05
98              M 2015-08-08      56.67      471336.91     144521.02
99              L 2012-02-15     502.54     3586605.09     889472.91

[92 rows x 5 columns]

In [19]:
data.drop(index=[6,8],columns=["Order_Priority","Unit_Cost"],inplace=True)

In [20]:
data

    Ship_Date  Total_Revenue  Total_Profit
10 2011-12-07       19103.44       7828.12
11 2014-08-19      455479.04     306097.92
12 2017-01-03      902980.64     606834.72
13 2017-02-13     5997054.98    1487261.02
14 2014-02-23      400558.73     122819.06
..        ...            ...           ...
95 2011-03-09       97040.64      65214.72
96 2011-12-28       58471.11      15103.47
97 2016-06-29      228779.10      93748.05
98 2015-08-08      471336.91     144521.02
99 2012-02-15     3586605.09     889472.91

[90 rows x 3 columns]

In [21]:
a = {
    "Ship_Date":"A",
    "Total_Revenue":"B"
}

In [22]:
data.rename(columns=a)

            A           B  Total_Profit
10 2011-12-07    19103.44       7828.12
11 2014-08-19   455479.04     306097.92
12 2017-01-03   902980.64     606834.72
13 2017-02-13  5997054.98    1487261.02
14 2014-02-23   400558.73     122819.06
..        ...         ...           ...
95 2011-03-09    97040.64      65214.72
96 2011-12-28    58471.11      15103.47
97 2016-06-29   228779.10      93748.05
98 2015-08-08   471336.91     144521.02
99 2012-02-15  3586605.09     889472.91

[90 rows x 3 columns]

In [23]:
data

    Ship_Date  Total_Revenue  Total_Profit
10 2011-12-07       19103.44       7828.12
11 2014-08-19      455479.04     306097.92
12 2017-01-03      902980.64     606834.72
13 2017-02-13     5997054.98    1487261.02
14 2014-02-23      400558.73     122819.06
..        ...            ...           ...
95 2011-03-09       97040.64      65214.72
96 2011-12-28       58471.11      15103.47
97 2016-06-29      228779.10      93748.05
98 2015-08-08      471336.91     144521.02
99 2012-02-15     3586605.09     889472.91

[90 rows x 3 columns]

In [24]:
data.rename(columns=a,inplace=True)

In [25]:
data

            A           B  Total_Profit
10 2011-12-07    19103.44       7828.12
11 2014-08-19   455479.04     306097.92
12 2017-01-03   902980.64     606834.72
13 2017-02-13  5997054.98    1487261.02
14 2014-02-23   400558.73     122819.06
..        ...         ...           ...
95 2011-03-09    97040.64      65214.72
96 2011-12-28    58471.11      15103.47
97 2016-06-29   228779.10      93748.05
98 2015-08-08   471336.91     144521.02
99 2012-02-15  3586605.09     889472.91

[90 rows x 3 columns]

In [26]:
data.columns

Index(['A', 'B', 'Total_Profit'], dtype='object')

In [27]:
data[['B','Total_Profit','A']]

             B  Total_Profit          A
10    19103.44       7828.12 2011-12-07
11   455479.04     306097.92 2014-08-19
12   902980.64     606834.72 2017-01-03
13  5997054.98    1487261.02 2017-02-13
14   400558.73     122819.06 2014-02-23
..         ...           ...        ...
95    97040.64      65214.72 2011-03-09
96    58471.11      15103.47 2011-12-28
97   228779.10      93748.05 2016-06-29
98   471336.91     144521.02 2015-08-08
99  3586605.09     889472.91 2012-02-15

[90 rows x 3 columns]

In [28]:
data = data1.copy()

In [29]:
data["Unit_Cost"].mean()

np.float64(191.048)

In [30]:
data["Order_Priority"].mode()

0    H
Name: Order_Priority, dtype: object

In [31]:
data[data["Country"] == "Russia"].count()

Region            1
Country           1
Item_Type         1
Sales_Channel     1
Order_Priority    1
Ship_Date         1
Unit_Cost         1
Total_Revenue     1
Total_Profit      1
dtype: int64

In [32]:
data[data["Order_Priority"] == 'H']

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.00,951410.50
7,Sub_Saharan Africa,Burkina Faso,Vegetables,Online,H,2012-07-27,90.93,1245112.92,510216.66
9,Sub_Saharan Africa,Senegal,Cereal,Online,H,2014-05-30,117.11,1356180.10,584073.87
10,Asia,Kyrgyzstan,Vegetables,Online,H,2011-12-07,90.93,19103.44,7828.12
11,Sub_Saharan Africa,Cape Verde,Clothes,Offline,H,2014-08-19,35.84,455479.04,306097.92
13,Central America and the Caribbean,Honduras,Household,Offline,H,2017-02-13,502.54,5997054.98,1487261.02
21,Europe,Portugal,Baby Food,Online,H,2015-03-09,159.42,324971.44,122029.78
23,Australia and Oceania,New Zealand,Fruits,Online,H,2014-04-10,6.92,20404.71,5270.67
25,Europe,France,Cosmetics,Online,H,2017-05-06,263.33,793518.00,315574.05
33,Asia,Myanmar,Household,Offline,H,2015-01-03,502.54,5513227.50,1367272.50
40,Sub_Saharan Africa,Niger,Personal Care,Online,H,2017-03-28,56.67,246415.95,75555.90
42,Sub_Saharan Africa,The Gambia,Cereal,Offline,H,2012-08-06,117.11,435466.90,187545.03
43,Europe,Slovakia,Vegetables,Online,H,2012-10-11,90.93,26344.26,10795.23
44,Asia,Myanmar,Clothes,Online,H,2015-11-18,35.84,648030.40,435499.20
45,Sub_Saharan Africa,Comoros,Cereal,Offline,H,2016-04-29,117.11,197883.40,85223.58
54,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Offline,H,2013-10-24,6.92,71253.21,18405.17
57,Europe,Austria,Cosmetics,Offline,H,2015-02-03,263.33,1244708.40,495007.89
59,Sub_Saharan Africa,Djibouti,Cosmetics,Offline,H,2014-04-19,263.33,3154398.00,1254472.05
60,Australia and Oceania,Australia,Cereal,Offline,H,2013-02-07,117.11,140287.40,60418.38
63,Middle East and North Africa,Libya,Clothes,Offline,H,2010-11-17,35.84,668356.48,449159.04
64,Central America and the Caribbean,Haiti,Cosmetics,Offline,H,2013-11-16,263.33,745426.00,296448.35
65,Sub_Saharan Africa,Rwanda,Cosmetics,Offline,H,2013-11-25,263.33,1957344.40,778415.99
68,Europe,Lithuania,Office Supplies,Offline,H,2010-11-17,524.96,5396577.27,1046233.75
73,Sub_Saharan Africa,Djibouti,Cereal,Online,H,2017-06-17,117.11,1780539.20,766835.04
78,Europe,Monaco,Baby Food,Offline,H,2012-02-06,159.42,2198981.92,825738.04
79,Australia and Oceania,Samoa,Cosmetics,Online,H,2013-07-08,263.33,4220728.80,1678540.98
82,Middle East and North Africa,Iran,Cosmetics,Online,H,2016-08-12,263.33,2836990.80,1128242.43
90,Sub_Saharan Africa,Sierra Leone,Office Supplies,Offline,H,2016-12-14,524.96,617347.08,119685.00
91,Australia and Oceania,Australia,Beverages,Offline,H,2014-11-07,31.79,445508.05,147031.74
93,Europe,Romania,Cosmetics,Online,H,2010-12-25,263.33,3458252.00,1375311.70

In [33]:
data["Sales_Channel"].mode()

0    Offline
1     Online
Name: Sales_Channel, dtype: object

In [34]:
data[(data["Sales_Channel"] == "Online") & (data["Order_Priority"] == "H")]

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
7,Sub_Saharan Africa,Burkina Faso,Vegetables,Online,H,2012-07-27,90.93,1245112.92,510216.66
9,Sub_Saharan Africa,Senegal,Cereal,Online,H,2014-05-30,117.11,1356180.10,584073.87
10,Asia,Kyrgyzstan,Vegetables,Online,H,2011-12-07,90.93,19103.44,7828.12
21,Europe,Portugal,Baby Food,Online,H,2015-03-09,159.42,324971.44,122029.78
23,Australia and Oceania,New Zealand,Fruits,Online,H,2014-04-10,6.92,20404.71,5270.67
25,Europe,France,Cosmetics,Online,H,2017-05-06,263.33,793518.00,315574.05
40,Sub_Saharan Africa,Niger,Personal Care,Online,H,2017-03-28,56.67,246415.95,75555.90
43,Europe,Slovakia,Vegetables,Online,H,2012-10-11,90.93,26344.26,10795.23
44,Asia,Myanmar,Clothes,Online,H,2015-11-18,35.84,648030.40,435499.20
73,Sub_Saharan Africa,Djibouti,Cereal,Online,H,2017-06-17,117.11,1780539.20,766835.04
79,Australia and Oceania,Samoa,Cosmetics,Online,H,2013-07-08,263.33,4220728.80,1678540.98
82,Middle East and North Africa,Iran,Cosmetics,Online,H,2016-08-12,263.33,2836990.80,1128242.43
93,Europe,Romania,Cosmetics,Online,H,2010-12-25,263.33,3458252.00,1375311.70

In [35]:
data[(data["Sales_Channel"] == "Online") & (data["Order_Priority"] == "H") & (data["Region"] == "Asia")]

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
10,Asia,Kyrgyzstan,Vegetables,Online,H,2011-12-07,90.93,19103.44,7828.12
44,Asia,Myanmar,Clothes,Online,H,2015-11-18,35.84,648030.40,435499.20

In [36]:
data["Unit_Cost"].std()

188.20818124855495

In [37]:
data[["Unit_Cost","Total_Profit"]].std()

Unit_Cost          188.208181
Total_Profit    438537.907060
dtype: float64

In [38]:
data1 = pd.read_csv(r"C:\Users\Admin\Downloads\Pandas last fillna  Resources 16922587502 (1).txt")

In [39]:
data1

         Date   Age  Sales        Day
0  01/01/2019  32.0    6.0     Monday
1  01/02/2019   NaN    9.0    Tuesday
2  01/10/2019  28.0    NaN  Wednesday
3  01/11/2019  32.0    7.0        NaN
4  01/12/2019   NaN    NaN     Monday
5  01/16/2019  32.0    NaN    Tuesday
6  01/17/2019   NaN    NaN        NaN
7  01/20/2019  34.0    8.0   Thrusday
8  01/21/2019  40.0   12.0    Tuesday

In [40]:
data1.isnull()

    Date    Age  Sales    Day
0  False  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4  False   True   True  False
5  False  False   True  False
6  False   True   True   True
7  False  False  False  False
8  False  False  False  False

In [41]:
data1.fillna("yash")

         Date   Age Sales        Day
0  01/01/2019  32.0   6.0     Monday
1  01/02/2019  yash   9.0    Tuesday
2  01/10/2019  28.0  yash  Wednesday
3  01/11/2019  32.0   7.0       yash
4  01/12/2019  yash  yash     Monday
5  01/16/2019  32.0  yash    Tuesday
6  01/17/2019  yash  yash       yash
7  01/20/2019  34.0   8.0   Thrusday
8  01/21/2019  40.0  12.0    Tuesday

In [42]:
data1.fillna(7)

         Date   Age  Sales        Day
0  01/01/2019  32.0    6.0     Monday
1  01/02/2019   7.0    9.0    Tuesday
2  01/10/2019  28.0    7.0  Wednesday
3  01/11/2019  32.0    7.0          7
4  01/12/2019   7.0    7.0     Monday
5  01/16/2019  32.0    7.0    Tuesday
6  01/17/2019   7.0    7.0          7
7  01/20/2019  34.0    8.0   Thrusday
8  01/21/2019  40.0   12.0    Tuesday

In [43]:
data1.fillna(method="ffill")

C:\Users\Admin\AppData\Local\Temp\ipykernel_5188\287217370.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1.fillna(method="ffill")

         Date   Age  Sales        Day
0  01/01/2019  32.0    6.0     Monday
1  01/02/2019  32.0    9.0    Tuesday
2  01/10/2019  28.0    9.0  Wednesday
3  01/11/2019  32.0    7.0  Wednesday
4  01/12/2019  32.0    7.0     Monday
5  01/16/2019  32.0    7.0    Tuesday
6  01/17/2019  32.0    7.0    Tuesday
7  01/20/2019  34.0    8.0   Thrusday
8  01/21/2019  40.0   12.0    Tuesday

In [44]:
data1.fillna(method="bfill")

C:\Users\Admin\AppData\Local\Temp\ipykernel_5188\2411069616.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1.fillna(method="bfill")

         Date   Age  Sales        Day
0  01/01/2019  32.0    6.0     Monday
1  01/02/2019  28.0    9.0    Tuesday
2  01/10/2019  28.0    7.0  Wednesday
3  01/11/2019  32.0    7.0     Monday
4  01/12/2019  32.0    8.0     Monday
5  01/16/2019  32.0    8.0    Tuesday
6  01/17/2019  34.0    8.0   Thrusday
7  01/20/2019  34.0    8.0   Thrusday
8  01/21/2019  40.0   12.0    Tuesday

In [45]:
data1["Day"].mode()[0]

'Tuesday'

In [46]:
a = {"Age":data1["Age"].mean(),"Sales":data1["Sales"].mean(),"Day":data1["Day"].mode()[0]}

In [47]:
data1.fillna(a)

         Date   Age  Sales        Day
0  01/01/2019  32.0    6.0     Monday
1  01/02/2019  33.0    9.0    Tuesday
2  01/10/2019  28.0    8.4  Wednesday
3  01/11/2019  32.0    7.0    Tuesday
4  01/12/2019  33.0    8.4     Monday
5  01/16/2019  32.0    8.4    Tuesday
6  01/17/2019  33.0    8.4    Tuesday
7  01/20/2019  34.0    8.0   Thrusday
8  01/21/2019  40.0   12.0    Tuesday