In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r"C:\Users\Admin\Downloads\Pandas last fillna  Resources 16922587502 (1).txt")

In [3]:
data

         Date   Age  Sales        Day
0  01/01/2019  32.0    6.0     Monday
1  01/02/2019   NaN    9.0    Tuesday
2  01/10/2019  28.0    NaN  Wednesday
3  01/11/2019  32.0    7.0        NaN
4  01/12/2019   NaN    NaN     Monday
5  01/16/2019  32.0    NaN    Tuesday
6  01/17/2019   NaN    NaN        NaN
7  01/20/2019  34.0    8.0   Thrusday
8  01/21/2019  40.0   12.0    Tuesday

In [4]:
data.fillna(method="ffill")

C:\Users\Admin\AppData\Local\Temp\ipykernel_28532\2321864255.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method="ffill")

         Date   Age  Sales        Day
0  01/01/2019  32.0    6.0     Monday
1  01/02/2019  32.0    9.0    Tuesday
2  01/10/2019  28.0    9.0  Wednesday
3  01/11/2019  32.0    7.0  Wednesday
4  01/12/2019  32.0    7.0     Monday
5  01/16/2019  32.0    7.0    Tuesday
6  01/17/2019  32.0    7.0    Tuesday
7  01/20/2019  34.0    8.0   Thrusday
8  01/21/2019  40.0   12.0    Tuesday

In [5]:
data.fillna(method="ffill",axis=1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_28532\1577049303.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method="ffill",axis=1)

         Date         Age       Sales         Day
0  01/01/2019        32.0         6.0      Monday
1  01/02/2019  01/02/2019         9.0     Tuesday
2  01/10/2019        28.0        28.0   Wednesday
3  01/11/2019        32.0         7.0         7.0
4  01/12/2019  01/12/2019  01/12/2019      Monday
5  01/16/2019        32.0        32.0     Tuesday
6  01/17/2019  01/17/2019  01/17/2019  01/17/2019
7  01/20/2019        34.0         8.0    Thrusday
8  01/21/2019        40.0        12.0     Tuesday

In [6]:
data

         Date   Age  Sales        Day
0  01/01/2019  32.0    6.0     Monday
1  01/02/2019   NaN    9.0    Tuesday
2  01/10/2019  28.0    NaN  Wednesday
3  01/11/2019  32.0    7.0        NaN
4  01/12/2019   NaN    NaN     Monday
5  01/16/2019  32.0    NaN    Tuesday
6  01/17/2019   NaN    NaN        NaN
7  01/20/2019  34.0    8.0   Thrusday
8  01/21/2019  40.0   12.0    Tuesday

In [7]:
data["Age"].mean()

np.float64(33.0)

In [8]:
data["Age"] = data["Age"].fillna(data["Age"].mean())

In [9]:
data

         Date   Age  Sales        Day
0  01/01/2019  32.0    6.0     Monday
1  01/02/2019  33.0    9.0    Tuesday
2  01/10/2019  28.0    NaN  Wednesday
3  01/11/2019  32.0    7.0        NaN
4  01/12/2019  33.0    NaN     Monday
5  01/16/2019  32.0    NaN    Tuesday
6  01/17/2019  33.0    NaN        NaN
7  01/20/2019  34.0    8.0   Thrusday
8  01/21/2019  40.0   12.0    Tuesday

In [10]:
data["Sales"].mean()

np.float64(8.4)

In [11]:
data["Sales"] = data["Sales"].fillna(data["Sales"].mean())

In [12]:
data

         Date   Age  Sales        Day
0  01/01/2019  32.0    6.0     Monday
1  01/02/2019  33.0    9.0    Tuesday
2  01/10/2019  28.0    8.4  Wednesday
3  01/11/2019  32.0    7.0        NaN
4  01/12/2019  33.0    8.4     Monday
5  01/16/2019  32.0    8.4    Tuesday
6  01/17/2019  33.0    8.4        NaN
7  01/20/2019  34.0    8.0   Thrusday
8  01/21/2019  40.0   12.0    Tuesday

In [13]:
data["Day"].mode()

0    Tuesday
Name: Day, dtype: object

In [14]:
data["Day"] = data["Day"].fillna(data["Day"].mode()[0])

In [15]:
data

         Date   Age  Sales        Day
0  01/01/2019  32.0    6.0     Monday
1  01/02/2019  33.0    9.0    Tuesday
2  01/10/2019  28.0    8.4  Wednesday
3  01/11/2019  32.0    7.0    Tuesday
4  01/12/2019  33.0    8.4     Monday
5  01/16/2019  32.0    8.4    Tuesday
6  01/17/2019  33.0    8.4    Tuesday
7  01/20/2019  34.0    8.0   Thrusday
8  01/21/2019  40.0   12.0    Tuesday

In [16]:
data1 = data.copy()

In [17]:
data

         Date   Age  Sales        Day
0  01/01/2019  32.0    6.0     Monday
1  01/02/2019  33.0    9.0    Tuesday
2  01/10/2019  28.0    8.4  Wednesday
3  01/11/2019  32.0    7.0    Tuesday
4  01/12/2019  33.0    8.4     Monday
5  01/16/2019  32.0    8.4    Tuesday
6  01/17/2019  33.0    8.4    Tuesday
7  01/20/2019  34.0    8.0   Thrusday
8  01/21/2019  40.0   12.0    Tuesday

In [18]:
data.fillna(54,limit=2)

         Date   Age  Sales        Day
0  01/01/2019  32.0    6.0     Monday
1  01/02/2019  33.0    9.0    Tuesday
2  01/10/2019  28.0    8.4  Wednesday
3  01/11/2019  32.0    7.0    Tuesday
4  01/12/2019  33.0    8.4     Monday
5  01/16/2019  32.0    8.4    Tuesday
6  01/17/2019  33.0    8.4    Tuesday
7  01/20/2019  34.0    8.0   Thrusday
8  01/21/2019  40.0   12.0    Tuesday

In [19]:
data.interpolate()

C:\Users\Admin\AppData\Local\Temp\ipykernel_28532\982976692.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  data.interpolate()

         Date   Age  Sales        Day
0  01/01/2019  32.0    6.0     Monday
1  01/02/2019  33.0    9.0    Tuesday
2  01/10/2019  28.0    8.4  Wednesday
3  01/11/2019  32.0    7.0    Tuesday
4  01/12/2019  33.0    8.4     Monday
5  01/16/2019  32.0    8.4    Tuesday
6  01/17/2019  33.0    8.4    Tuesday
7  01/20/2019  34.0    8.0   Thrusday
8  01/21/2019  40.0   12.0    Tuesday

In [20]:
data.isnull().mean()*100

Date     0.0
Age      0.0
Sales    0.0
Day      0.0
dtype: float64

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    9 non-null      object
 1   Age     9 non-null      float64
 2   Sales   9 non-null      float64
 3   Day     9 non-null      object
dtypes: float64(2), object(2)
memory usage: 420.0+ bytes

In [22]:
data = pd.read_csv(r"C:\Users\Admin\Downloads\Pandas last fillna  Resources 16922587502 (1).txt",parse_dates=["Date"])

In [23]:
data

        Date   Age  Sales        Day
0 2019-01-01  32.0    6.0     Monday
1 2019-01-02   NaN    9.0    Tuesday
2 2019-01-10  28.0    NaN  Wednesday
3 2019-01-11  32.0    7.0        NaN
4 2019-01-12   NaN    NaN     Monday
5 2019-01-16  32.0    NaN    Tuesday
6 2019-01-17   NaN    NaN        NaN
7 2019-01-20  34.0    8.0   Thrusday
8 2019-01-21  40.0   12.0    Tuesday

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    9 non-null      datetime64[ns]
 1   Age     6 non-null      float64
 2   Sales   5 non-null      float64
 3   Day     7 non-null      object
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 420.0+ bytes

In [25]:
data = data1.copy()

In [26]:
data

         Date   Age  Sales        Day
0  01/01/2019  32.0    6.0     Monday
1  01/02/2019  33.0    9.0    Tuesday
2  01/10/2019  28.0    8.4  Wednesday
3  01/11/2019  32.0    7.0    Tuesday
4  01/12/2019  33.0    8.4     Monday
5  01/16/2019  32.0    8.4    Tuesday
6  01/17/2019  33.0    8.4    Tuesday
7  01/20/2019  34.0    8.0   Thrusday
8  01/21/2019  40.0   12.0    Tuesday

In [27]:
data["Date"] = pd.to_datetime(data["Date"])

In [28]:
data

        Date   Age  Sales        Day
0 2019-01-01  32.0    6.0     Monday
1 2019-01-02  33.0    9.0    Tuesday
2 2019-01-10  28.0    8.4  Wednesday
3 2019-01-11  32.0    7.0    Tuesday
4 2019-01-12  33.0    8.4     Monday
5 2019-01-16  32.0    8.4    Tuesday
6 2019-01-17  33.0    8.4    Tuesday
7 2019-01-20  34.0    8.0   Thrusday
8 2019-01-21  40.0   12.0    Tuesday

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    9 non-null      datetime64[ns]
 1   Age     9 non-null      float64
 2   Sales   9 non-null      float64
 3   Day     9 non-null      object
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 420.0+ bytes

In [30]:
data["Date"].dt.day_name()

0      Tuesday
1    Wednesday
2     Thursday
3       Friday
4     Saturday
5    Wednesday
6     Thursday
7       Sunday
8       Monday
Name: Date, dtype: object

In [31]:
data["Date"].dt.month

0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
Name: Date, dtype: int32

In [32]:
data["Date"].dt.year

0    2019
1    2019
2    2019
3    2019
4    2019
5    2019
6    2019
7    2019
8    2019
Name: Date, dtype: int32

In [33]:
data["Day"] = data["Day"].fillna(data["Date"].dt.day_name())

In [34]:
data

        Date   Age  Sales        Day
0 2019-01-01  32.0    6.0     Monday
1 2019-01-02  33.0    9.0    Tuesday
2 2019-01-10  28.0    8.4  Wednesday
3 2019-01-11  32.0    7.0    Tuesday
4 2019-01-12  33.0    8.4     Monday
5 2019-01-16  32.0    8.4    Tuesday
6 2019-01-17  33.0    8.4    Tuesday
7 2019-01-20  34.0    8.0   Thrusday
8 2019-01-21  40.0   12.0    Tuesday

In [35]:
data.dropna(how="any")

        Date   Age  Sales        Day
0 2019-01-01  32.0    6.0     Monday
1 2019-01-02  33.0    9.0    Tuesday
2 2019-01-10  28.0    8.4  Wednesday
3 2019-01-11  32.0    7.0    Tuesday
4 2019-01-12  33.0    8.4     Monday
5 2019-01-16  32.0    8.4    Tuesday
6 2019-01-17  33.0    8.4    Tuesday
7 2019-01-20  34.0    8.0   Thrusday
8 2019-01-21  40.0   12.0    Tuesday

In [36]:
data.dropna(how="all")

        Date   Age  Sales        Day
0 2019-01-01  32.0    6.0     Monday
1 2019-01-02  33.0    9.0    Tuesday
2 2019-01-10  28.0    8.4  Wednesday
3 2019-01-11  32.0    7.0    Tuesday
4 2019-01-12  33.0    8.4     Monday
5 2019-01-16  32.0    8.4    Tuesday
6 2019-01-17  33.0    8.4    Tuesday
7 2019-01-20  34.0    8.0   Thrusday
8 2019-01-21  40.0   12.0    Tuesday

In [37]:
data.drop("Date",axis=1,inplace=True)

In [38]:
data.dropna(how="all")

    Age  Sales        Day
0  32.0    6.0     Monday
1  33.0    9.0    Tuesday
2  28.0    8.4  Wednesday
3  32.0    7.0    Tuesday
4  33.0    8.4     Monday
5  32.0    8.4    Tuesday
6  33.0    8.4    Tuesday
7  34.0    8.0   Thrusday
8  40.0   12.0    Tuesday

In [39]:
data.dropna(how="any",axis=1)

    Age  Sales        Day
0  32.0    6.0     Monday
1  33.0    9.0    Tuesday
2  28.0    8.4  Wednesday
3  32.0    7.0    Tuesday
4  33.0    8.4     Monday
5  32.0    8.4    Tuesday
6  33.0    8.4    Tuesday
7  34.0    8.0   Thrusday
8  40.0   12.0    Tuesday

In [40]:
new = data.dropna(thresh=4)

In [41]:
new

Empty DataFrame
Columns: [Age, Sales, Day]
Index: []

In [42]:
new.to_excel("new2.xlsx")

In [43]:
data = {"StudentName": ["Reena", "Anil", "Mansi", "Jaman","Reena"],
        "Age": [24, 28, 26, 24,24],
        "Sex": ["Female", "Male", "Female", "Male","Female"]}
df = pd.DataFrame(data)
print(df)

  StudentName  Age     Sex
0       Reena   24  Female
1        Anil   28    Male
2       Mansi   26  Female
3       Jaman   24    Male
4       Reena   24  Female

In [44]:
df.drop_duplicates(keep="first")

  StudentName  Age     Sex
0       Reena   24  Female
1        Anil   28    Male
2       Mansi   26  Female
3       Jaman   24    Male

In [45]:
df.drop_duplicates(keep="last")

  StudentName  Age     Sex
1        Anil   28    Male
2       Mansi   26  Female
3       Jaman   24    Male
4       Reena   24  Female

In [46]:
df.drop_duplicates(keep=False)

  StudentName  Age     Sex
1        Anil   28    Male
2       Mansi   26  Female
3       Jaman   24    Male

In [47]:
df1 = df.copy()

In [48]:
data = {"StudentName": ["Reena", "Anil", "Mansi", "Jaman","Reena"],
        "Age": [25, 28, 26, 24,24],
        "Sex": ["Female", "Male", "Female", "Male","Female"]}
df = pd.DataFrame(data)
print(df)

  StudentName  Age     Sex
0       Reena   25  Female
1        Anil   28    Male
2       Mansi   26  Female
3       Jaman   24    Male
4       Reena   24  Female

In [49]:
df.drop_duplicates("StudentName")

  StudentName  Age     Sex
0       Reena   25  Female
1        Anil   28    Male
2       Mansi   26  Female
3       Jaman   24    Male

In [50]:
df.sort_values("StudentName")

  StudentName  Age     Sex
1        Anil   28    Male
3       Jaman   24    Male
2       Mansi   26  Female
0       Reena   25  Female
4       Reena   24  Female

In [51]:
df.sort_values("Age")

  StudentName  Age     Sex
3       Jaman   24    Male
4       Reena   24  Female
0       Reena   25  Female
2       Mansi   26  Female
1        Anil   28    Male

In [52]:
df.sort_values("StudentName",ascending=False)

  StudentName  Age     Sex
0       Reena   25  Female
4       Reena   24  Female
2       Mansi   26  Female
3       Jaman   24    Male
1        Anil   28    Male

In [53]:
df.sort_values(["StudentName","Age"])

  StudentName  Age     Sex
1        Anil   28    Male
3       Jaman   24    Male
2       Mansi   26  Female
4       Reena   24  Female
0       Reena   25  Female

In [54]:
df.sort_values(["StudentName","Age"],ascending=[True,False])

  StudentName  Age     Sex
1        Anil   28    Male
3       Jaman   24    Male
2       Mansi   26  Female
0       Reena   25  Female
4       Reena   24  Female