In [1]:
import pandas as pd

In [2]:
file1 = pd.read_csv(r"C:\Users\Admin\Downloads\Pandas Session 2 join Resources 16922586001 (1).txt")

In [3]:
file1

,use_id,user_id,platform,platform_version,device,use_type_id
0,22782,26980,ios,10.2,"iPhone7,2",2
1,22783,29628,android,6.0,Nexus 5,3
2,22784,28473,android,5.1,SM-G903F,1
3,22785,15200,ios,10.2,"iPhone7,2",3
4,22786,28239,android,6.0,ONE E1003,1
...,...,...,...,...,...,...
267,23049,29725,android,6.0,SM-G900F,1
268,23050,29726,ios,10.2,"iPhone7,2",3
269,23051,29726,ios,10.2,"iPhone7,2",3
270,23052,29727,ios,10.1,"iPhone8,4",3
271,23053,20257,android,5.1,Vodafone Smart ultra 6,1

In [4]:
file2 = pd.read_csv(r"C:\Users\Admin\Downloads\Pandas Session 2 join Resources 16922586000 (1).txt")

In [5]:
file2

     outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id
0                      21.97                    4.82     1557.33   22787
1                    1710.08                  136.88     7267.55   22788
2                    1710.08                  136.88     7267.55   22789
3                      94.46                   35.17      519.12   22790
4                      71.59                   79.26     1557.33   22792
..                       ...                     ...         ...     ...
235                   260.66                   68.44      896.96   25008
236                    97.12                   36.50     2815.00   25040
237                   355.93                   12.37     6828.09   25046
238                   632.06                  120.46     1453.16   25058
239                   488.70                  906.92     3089.85   25220

[240 rows x 4 columns]

In [6]:
pd.merge(file2,file1)

,outgoing_mins_per_month,outgoing_sms_per_month,monthly_mb,use_id,user_id,platform,platform_version,device,use_type_id
0,21.97,4.82,1557.33,22787,12921,android,4.3,GT-I9505,1
1,1710.08,136.88,7267.55,22788,28714,android,6.0,SM-G930F,1
2,1710.08,136.88,7267.55,22789,28714,android,6.0,SM-G930F,1
3,94.46,35.17,519.12,22790,29592,android,5.1,D2303,1
4,71.59,79.26,1557.33,22792,28217,android,5.1,SM-G361F,1
...,...,...,...,...,...,...,...,...,...
154,198.59,90.49,5191.12,23043,28953,android,6.0,SM-G900F,1
155,198.59,90.49,3114.67,23044,28953,android,6.0,SM-G900F,1
156,106.65,82.13,5191.12,23046,29454,android,6.0,Moto G (4),1
157,344.53,20.53,519.12,23049,29725,android,6.0,SM-G900F,1
158,42.75,46.83,5191.12,23053,20257,android,5.1,Vodafone Smart ultra 6,1

In [7]:
pd.merge(file2,file1,how="left")

,outgoing_mins_per_month,outgoing_sms_per_month,monthly_mb,use_id,user_id,platform,platform_version,device,use_type_id
0,21.97,4.82,1557.33,22787,12921.0,android,4.3,GT-I9505,1.0
1,1710.08,136.88,7267.55,22788,28714.0,android,6.0,SM-G930F,1.0
2,1710.08,136.88,7267.55,22789,28714.0,android,6.0,SM-G930F,1.0
3,94.46,35.17,519.12,22790,29592.0,android,5.1,D2303,1.0
4,71.59,79.26,1557.33,22792,28217.0,android,5.1,SM-G361F,1.0
...,...,...,...,...,...,...,...,...,...
235,260.66,68.44,896.96,25008,NaN,NaN,NaN,NaN,NaN
236,97.12,36.50,2815.00,25040,NaN,NaN,NaN,NaN,NaN
237,355.93,12.37,6828.09,25046,NaN,NaN,NaN,NaN,NaN
238,632.06,120.46,1453.16,25058,NaN,NaN,NaN,NaN,NaN
239,488.70,906.92,3089.85,25220,NaN,NaN,NaN,NaN,NaN

In [8]:
pd.merge(file2,file1,how="right")

,outgoing_mins_per_month,outgoing_sms_per_month,monthly_mb,use_id,user_id,platform,platform_version,device,use_type_id
0,NaN,NaN,NaN,22782,26980,ios,10.2,"iPhone7,2",2
1,NaN,NaN,NaN,22783,29628,android,6.0,Nexus 5,3
2,NaN,NaN,NaN,22784,28473,android,5.1,SM-G903F,1
3,NaN,NaN,NaN,22785,15200,ios,10.2,"iPhone7,2",3
4,NaN,NaN,NaN,22786,28239,android,6.0,ONE E1003,1
...,...,...,...,...,...,...,...,...,...
267,344.53,20.53,519.12,23049,29725,android,6.0,SM-G900F,1
268,NaN,NaN,NaN,23050,29726,ios,10.2,"iPhone7,2",3
269,NaN,NaN,NaN,23051,29726,ios,10.2,"iPhone7,2",3
270,NaN,NaN,NaN,23052,29727,ios,10.1,"iPhone8,4",3
271,42.75,46.83,5191.12,23053,20257,android,5.1,Vodafone Smart ultra 6,1

In [9]:
pd.merge(file2,file1,how="left",on="use_id")

,outgoing_mins_per_month,outgoing_sms_per_month,monthly_mb,use_id,user_id,platform,platform_version,device,use_type_id
0,21.97,4.82,1557.33,22787,12921.0,android,4.3,GT-I9505,1.0
1,1710.08,136.88,7267.55,22788,28714.0,android,6.0,SM-G930F,1.0
2,1710.08,136.88,7267.55,22789,28714.0,android,6.0,SM-G930F,1.0
3,94.46,35.17,519.12,22790,29592.0,android,5.1,D2303,1.0
4,71.59,79.26,1557.33,22792,28217.0,android,5.1,SM-G361F,1.0
...,...,...,...,...,...,...,...,...,...
235,260.66,68.44,896.96,25008,NaN,NaN,NaN,NaN,NaN
236,97.12,36.50,2815.00,25040,NaN,NaN,NaN,NaN,NaN
237,355.93,12.37,6828.09,25046,NaN,NaN,NaN,NaN,NaN
238,632.06,120.46,1453.16,25058,NaN,NaN,NaN,NaN,NaN
239,488.70,906.92,3089.85,25220,NaN,NaN,NaN,NaN,NaN

In [10]:
file1.head(2)

   use_id  user_id platform  platform_version     device  use_type_id
0   22782    26980      ios              10.2  iPhone7,2            2
1   22783    29628  android               6.0    Nexus 5            3

In [11]:
file2.head(2)

   outgoing_mins_per_month  outgoing_sms_per_month  monthly_mb  use_id
0                    21.97                    4.82     1557.33   22787
1                  1710.08                  136.88     7267.55   22788

In [12]:
data = pd.merge(file2,file1)

In [13]:
mer = pd.merge(data[["outgoing_mins_per_month","use_id"]],data[["device","use_id"]],how="left",on="use_id")

In [14]:
mer

     outgoing_mins_per_month  use_id                  device
0                      21.97   22787                GT-I9505
1                    1710.08   22788                SM-G930F
2                    1710.08   22789                SM-G930F
3                      94.46   22790                   D2303
4                      71.59   22792                SM-G361F
..                       ...     ...                     ...
154                   198.59   23043                SM-G900F
155                   198.59   23044                SM-G900F
156                   106.65   23046              Moto G (4)
157                   344.53   23049                SM-G900F
158                    42.75   23053  Vodafone Smart ultra 6

[159 rows x 3 columns]

In [15]:
# Creating first dataframe 
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'], 
                    'B': ['B0', 'B1', 'B2', 'B3'], 
                    'C': ['C0', 'C1', 'C2', 'C3'], 
                    'D': ['D0', 'D1', 'D2', 'D3']}) 
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [16]:
# Creating second dataframe 
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'], 
                    'B': ['B4', 'B5', 'B6', 'B7'], 
                    'C': ['C4', 'C5', 'C6', 'C7'], 
                    'D': ['D4', 'D5', 'D6', 'D7']})
df2

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [17]:
# Creating third dataframe 
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'], 
                    'B': ['B8', 'B9', 'B10', 'B11'], 
                    'C': ['C8', 'C9', 'C10', 'C11'], 
                    'D': ['D8', 'D9', 'D10', 'D11']})
df3

     A    B    C    D
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [18]:
data1 = pd.concat([df1,df2,df3])

In [19]:
data1

     A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A4   B4   C4   D4
1   A5   B5   C5   D5
2   A6   B6   C6   D6
3   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [20]:
data1.reset_index()

    index    A    B    C    D
0       0   A0   B0   C0   D0
1       1   A1   B1   C1   D1
2       2   A2   B2   C2   D2
3       3   A3   B3   C3   D3
4       0   A4   B4   C4   D4
5       1   A5   B5   C5   D5
6       2   A6   B6   C6   D6
7       3   A7   B7   C7   D7
8       0   A8   B8   C8   D8
9       1   A9   B9   C9   D9
10      2  A10  B10  C10  D10
11      3  A11  B11  C11  D11

In [21]:
data1

     A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A4   B4   C4   D4
1   A5   B5   C5   D5
2   A6   B6   C6   D6
3   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [22]:
data = pd.read_excel(r"C:\Users\Admin\OneDrive\Desktop\Library Resources\Pandas\Pandas Session 1 Resources 16922586003.xlsx")

In [23]:
data

,Region,Country,Item_Type,Sales_Channel,Order_Priority,Ship_Date,Unit_Cost,Total_Revenue,Total_Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-06-27,159.42,2533654.00,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-09-15,117.11,576782.80,248406.36
2,Europe,Russia,Office Supplies,Offline,L,2014-08-05,524.96,1158502.59,224598.75
3,Sub_Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-05-07,6.92,75591.66,19525.82
4,Sub_Saharan Africa,Rwanda,Office Supplies,Offline,L,2013-06-02,524.96,3296425.02,639077.50
...,...,...,...,...,...,...,...,...,...
95,Sub_Saharan Africa,Mali,Clothes,Online,M,2011-03-09,35.84,97040.64,65214.72
96,Asia,Malaysia,Fruits,Offline,L,2011-12-28,6.92,58471.11,15103.47
97,Sub_Saharan Africa,Sierra Leone,Vegetables,Offline,C,2016-06-29,90.93,228779.10,93748.05
98,North America,Mexico,Personal Care,Offline,M,2015-08-08,56.67,471336.91,144521.02
99,Sub_Saharan Africa,Mozambique,Household,Offline,L,2012-02-15,502.54,3586605.09,889472.91

In [24]:
data.groupby("Sales_Channel")["Country"].count()

Sales_Channel
Offline    50
Online     50
Name: Country, dtype: int64

In [25]:
data.groupby(["Sales_Channel","Country"])[["Order_Priority","Region"]].count()

                              Order_Priority  Region
Sales_Channel Country
Offline       Angola                       1       1
              Australia                    2       2
              Austria                      1       1
              Belize                       1       1
              Cameroon                     1       1
...                                      ...     ...
Online        Syria                        1       1
              The Gambia                   1       1
              Turkmenistan                 1       1
              United Kingdom               1       1
              Zambia                       1       1

[87 rows x 2 columns]

In [26]:
data.groupby(["Order_Priority","Sales_Channel"])[["Unit_Cost","Total_Profit"]].mean()

                               Unit_Cost   Total_Profit
Order_Priority Sales_Channel
C              Offline        119.486923  278870.439231
               Online         134.111111  347001.416667
H              Offline        228.757647  580930.938235
               Online         139.936923  539674.894615
L              Offline        294.681667  528441.738333
               Online         143.524667  301161.800000
M              Offline        232.845000  634785.518750
               Online         237.276923  353173.719231

In [27]:
data.groupby(["Sales_Channel","Order_Priority"])[["Unit_Cost","Total_Profit"]].mean()

                               Unit_Cost   Total_Profit
Sales_Channel Order_Priority
Offline       C               119.486923  278870.439231
              H               228.757647  580930.938235
              L               294.681667  528441.738333
              M               232.845000  634785.518750
Online        C               134.111111  347001.416667
              H               139.936923  539674.894615
              L               143.524667  301161.800000
              M               237.276923  353173.719231

In [28]:
data.groupby(["Sales_Channel","Order_Priority"])[["Unit_Cost","Total_Profit"]].count()

                              Unit_Cost  Total_Profit
Sales_Channel Order_Priority
Offline       C                      13            13
              H                      17            17
              L                      12            12
              M                       8             8
Online        C                       9             9
              H                      13            13
              L                      15            15
              M                      13            13

In [29]:
data.groupby(["Sales_Channel","Order_Priority"])[["Unit_Cost","Total_Profit"]].agg(["mean","count","median"])

                               Unit_Cost                  Total_Profit        \
                                    mean count   median           mean count
Sales_Channel Order_Priority
Offline       C               119.486923    13   35.840  278870.439231    13
              H               228.757647    17  159.420  580930.938235    17
              L               294.681667    12  382.935  528441.738333    12
              M               232.845000     8  211.375  634785.518750     8
Online        C               134.111111     9   35.840  347001.416667     9
              H               139.936923    13  117.110  539674.894615    13
              L               143.524667    15   90.930  301161.800000    15
              M               237.276923    13  117.110  353173.719231    13


                                  median
Sales_Channel Order_Priority
Offline       C               127722.960
              H               449159.040
              L               465988.290
              M               484665.995
Online        C               248406.360
              H               435499.200
              L               225246.900
              M               272672.400

In [30]:
pd.pivot_table(data,index=["Sales_Channel","Order_Priority"],aggfunc="count")

                              Country  Item_Type  Region  Ship_Date  \
Sales_Channel Order_Priority
Offline       C                    13         13      13         13
              H                    17         17      17         17
              L                    12         12      12         12
              M                     8          8       8          8
Online        C                     9          9       9          9
              H                    13         13      13         13
              L                    15         15      15         15
              M                    13         13      13         13

                              Total_Profit  Total_Revenue  Unit_Cost
Sales_Channel Order_Priority
Offline       C                         13             13         13
              H                         17             17         17
              L                         12             12         12
              M                          8              8          8
Online        C                          9              9          9
              H                         13             13         13
              L                         15             15         15
              M                         13             13         13

In [31]:
pd.pivot_table(data,index=["Sales_Channel","Order_Priority"],columns=["Unit_Cost","Total_Profit"],aggfunc="count")

                                Country                                   \
Unit_Cost                        6.92
Total_Profit                 1258.02    1621.93    5270.67    9119.44
Sales_Channel Order_Priority
Offline       C                     NaN        NaN        NaN        NaN
              H                     NaN        NaN        NaN        NaN
              L                     NaN        NaN        NaN        NaN
              M                     NaN        NaN        NaN        NaN
Online        C                     NaN        NaN        NaN        NaN
              H                     NaN        NaN        1.0        NaN
              L                     NaN        1.0        NaN        1.0
              M                     1.0        NaN        NaN        NaN

                                                                          \
Unit_Cost
Total_Profit                 13009.18   14031.02   15103.47   18405.17
Sales_Channel Order_Priority
Offline       C                     NaN        NaN        NaN        NaN
              H                     NaN        NaN        NaN        1.0
              L                     NaN        NaN        1.0        NaN
              M                     NaN        NaN        NaN        NaN
Online        C                     NaN        NaN        NaN        NaN
              H                     NaN        NaN        NaN        NaN
              L                     NaN        1.0        NaN        NaN
              M                     1.0        NaN        NaN        NaN

                                                    ... Total_Revenue  \
Unit_Cost                                           ...        524.96
Total_Profit                 19525.82   23150.46    ...    224598.75
Sales_Channel Order_Priority                        ...
Offline       C                     NaN        NaN  ...           NaN
              H                     NaN        NaN  ...           NaN
              L                     NaN        NaN  ...           1.0
              M                     NaN        NaN  ...           NaN
Online        C                     1.0        NaN  ...           NaN
              H                     NaN        NaN  ...           NaN
              L                     NaN        1.0  ...           NaN
              M                     NaN        NaN  ...           NaN

                                                                          \
Unit_Cost
Total_Profit                 255151.25  369155.00  436446.25  503358.75
Sales_Channel Order_Priority
Offline       C                     NaN        NaN        NaN        NaN
              H                     NaN        NaN        NaN        NaN
              L                     NaN        NaN        NaN        NaN
              M                     NaN        NaN        1.0        NaN
Online        C                     NaN        1.0        NaN        NaN
              H                     NaN        NaN        NaN        NaN
              L                     NaN        NaN        NaN        NaN
              M                     1.0        NaN        NaN        1.0

                                                                          \
Unit_Cost
Total_Profit                 632512.50  639077.50  696647.50  846885.00
Sales_Channel Order_Priority
Offline       C                     NaN        NaN        NaN        NaN
              H                     NaN        NaN        NaN        NaN
              L                     NaN        1.0        NaN        NaN
              M                     NaN        NaN        NaN        NaN
Online        C                     NaN        NaN        NaN        NaN
              H                     NaN        NaN        NaN        NaN
              L                     NaN        NaN        NaN        1.0
              M                     1.0        NaN        1.0        NaN


Unit_Cost
Total_Profit                 1046233.75
Sales_Channel Order_Priority
Offline       C                     NaN
              H                     1.0
              L                     NaN
              M                     NaN
Online        C                     NaN
              H                     NaN
              L                     NaN
              M                     NaN

[8 rows x 500 columns]

In [32]:
data.groupby("Region")[["Total_Profit","Unit_Cost"]].mean()

                                    Total_Profit   Unit_Cost
Region
Asia                               555804.170000  239.587273
Australia and Oceania              429287.275455  154.744545
Central America and the Caribbean  406701.121429  157.817143
Europe                             503769.937727  223.166364
Middle East and North Africa       576119.186000  152.450000
North America                      485980.920000  205.293333
Sub_Saharan Africa                 338422.538889  183.677500

In [33]:
import pandas as pd

In [34]:
data = pd.read_excel(r"C:\Users\Admin\OneDrive\Desktop\Library Resources\Pandas\Pandas Session 1 Resources 16922586003.xlsx")

In [35]:
pd.crosstab(data["Region"],data["Sales_Channel"])

Sales_Channel                      Offline  Online
Region
Asia                                     6       5
Australia and Oceania                    4       7
Central America and the Caribbean        5       2
Europe                                   9      13
Middle East and North Africa             2       8
North America                            3       0
Sub_Saharan Africa                      21      15

In [36]:
pd.crosstab(data["Sales_Channel"],data["Item_Type"])

Item_Type,Baby Food,Beverages,Cereal,Clothes,Cosmetics,Fruits,Household,Meat,Office Supplies,Personal Care,Snacks,Vegetables
Sales_Channel,,,,,,,,,,,,
Offline,3,6,3,6,7,2,8,0,6,7,0,2
Online,4,2,4,7,6,8,1,2,6,3,3,4