In [1]:
import pandas as pd

In [2]:
pd.read_csv(r"C:\Users\Admin\OneDrive\Desktop\ML\ML-3 Feature Encoding Resource16931320640.txt")

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [3]:
a = ["none","medium","very high","low","high"]

In [4]:
data = pd.DataFrame(a,columns=["yash"])

In [5]:
data

        yash
0       none
1     medium
2  very high
3        low
4       high

In [6]:
b = [0,2,4,1,3]

In [7]:
data["en_val"] = b

In [8]:
data

        yash  en_val
0       none       0
1     medium       2
2  very high       4
3        low       1
4       high       3

In [9]:
data

        yash  en_val
0       none       0
1     medium       2
2  very high       4
3        low       1
4       high       3

In [10]:
data.replace(a,b)

C:\Users\Admin\AppData\Local\Temp\ipykernel_960\1936185244.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace(a,b)

   yash  en_val
0     0       0
1     2       2
2     4       4
3     1       1
4     3       3

In [11]:
c = ["S","M","L","S","M","L","S","M","L","S","M","L","S","M","L"]

In [12]:
data = pd.DataFrame(c)

In [13]:
data

    0
0   S
1   M
2   L
3   S
4   M
5   L
6   S
7   M
8   L
9   S
10  M
11  L
12  S
13  M
14  L

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le = LabelEncoder()

In [16]:
le.fit_transform(data[0])

array([2, 1, 0, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2, 1, 0])

In [17]:
data["en_val"] = le.fit_transform(data[0])

In [18]:
data

    0  en_val
0   S       2
1   M       1
2   L       0
3   S       2
4   M       1
5   L       0
6   S       2
7   M       1
8   L       0
9   S       2
10  M       1
11  L       0
12  S       2
13  M       1
14  L       0

In [19]:
data.drop(0,axis=1,inplace=True)

In [20]:
data

    en_val
0        2
1        1
2        0
3        2
4        1
5        0
6        2
7        1
8        0
9        2
10       1
11       0
12       2
13       1
14       0

In [21]:
data

    en_val
0        2
1        1
2        0
3        2
4        1
5        0
6        2
7        1
8        0
9        2
10       1
11       0
12       2
13       1
14       0

In [22]:
le.inverse_transform([0,1,2])

array(['L', 'M', 'S'], dtype=object)

In [23]:
le.inverse_transform(data["en_val"])

array(['S', 'M', 'L', 'S', 'M', 'L', 'S', 'M', 'L', 'S', 'M', 'L', 'S',
       'M', 'L'], dtype=object)

In [24]:
data

    en_val
0        2
1        1
2        0
3        2
4        1
5        0
6        2
7        1
8        0
9        2
10       1
11       0
12       2
13       1
14       0

In [25]:
data["en_val"].unique()

array([2, 1, 0])

In [26]:
data.describe()

          en_val
count  15.000000
mean    1.000000
std     0.845154
min     0.000000
25%     0.000000
50%     1.000000
75%     2.000000
max     2.000000

In [27]:
data = pd.get_dummies(data["en_val"])

In [28]:
data

        0      1      2
0   False  False   True
1   False   True  False
2    True  False  False
3   False  False   True
4   False   True  False
5    True  False  False
6   False  False   True
7   False   True  False
8    True  False  False
9   False  False   True
10  False   True  False
11   True  False  False
12  False  False   True
13  False   True  False
14   True  False  False

In [29]:
c

['S', 'M', 'L', 'S', 'M', 'L', 'S', 'M', 'L', 'S', 'M', 'L', 'S', 'M', 'L']

In [30]:
c = pd.DataFrame(c)
c

    0
0   S
1   M
2   L
3   S
4   M
5   L
6   S
7   M
8   L
9   S
10  M
11  L
12  S
13  M
14  L

In [31]:
data["val"] = c

In [32]:
data

        0      1      2 val
0   False  False   True   S
1   False   True  False   M
2    True  False  False   L
3   False  False   True   S
4   False   True  False   M
5    True  False  False   L
6   False  False   True   S
7   False   True  False   M
8    True  False  False   L
9   False  False   True   S
10  False   True  False   M
11   True  False  False   L
12  False  False   True   S
13  False   True  False   M
14   True  False  False   L

In [33]:
data.drop("val",axis=1,inplace=True)

In [34]:
data

        0      1      2
0   False  False   True
1   False   True  False
2    True  False  False
3   False  False   True
4   False   True  False
5    True  False  False
6   False  False   True
7   False   True  False
8    True  False  False
9   False  False   True
10  False   True  False
11   True  False  False
12  False  False   True
13  False   True  False
14   True  False  False

In [35]:
pd.concat([data,c],axis=1)

        0      1      2  0
0   False  False   True  S
1   False   True  False  M
2    True  False  False  L
3   False  False   True  S
4   False   True  False  M
5    True  False  False  L
6   False  False   True  S
7   False   True  False  M
8    True  False  False  L
9   False  False   True  S
10  False   True  False  M
11   True  False  False  L
12  False  False   True  S
13  False   True  False  M
14   True  False  False  L

In [36]:
data = pd.read_csv(r"C:\Users\Admin\OneDrive\Desktop\ML\ML-3 Feature Encoding Resource16931320640.txt")

In [37]:
data

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [38]:
data["marital-status"].unique()

array(['Never-married', 'Married-civ-spouse', 'Widowed', 'Divorced',
       'Separated', 'Married-spouse-absent', 'Married-AF-spouse'],
      dtype=object)

In [39]:
le.fit_transform(data["marital-status"])

array([4, 2, 2, ..., 6, 4, 2])

In [40]:
data["marital-status"] = le.fit_transform(data["marital-status"])

In [41]:
data.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,4,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,2,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,2,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,2,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,4,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [42]:
le.inverse_transform([4])

array(['Never-married'], dtype=object)