In [1]:
import pandas as pd

In [2]:
data = pd.DataFrame([29,10,45,46,68,34,65,89,400,92,77,66,69,65,80,77,21,37,42],columns=["value"])
# data = pd.DataFrame([29,10,45,46,68,34,65,89,400,92,77,66,69,65,80,77,21,37,42,2541,5441,1008,3448,1082003],columns=["value"])

In [3]:
data

    value
0      29
1      10
2      45
3      46
4      68
5      34
6      65
7      89
8     400
9      92
10     77
11     66
12     69
13     65
14     80
15     77
16     21
17     37
18     42

In [4]:
import numpy as np

In [5]:
q1,q3 = np.percentile(data["value"],[25,75])
q1,q3

(np.float64(39.5), np.float64(77.0))

In [6]:
iqr = q3-q1
iqr

np.float64(37.5)

In [7]:
ub = q3 + 1.5 * iqr
lb = q1 - 1.5 * iqr
ub,lb

(np.float64(133.25), np.float64(-16.75))

In [8]:
data[(data["value"]>ub) | (data["value"]<lb)]

   value
8    400

In [9]:
data[(data["value"]<ub) & (data["value"]>lb)]

    value
0      29
1      10
2      45
3      46
4      68
5      34
6      65
7      89
9      92
10     77
11     66
12     69
13     65
14     80
15     77
16     21
17     37
18     42

In [10]:
ub = q3 + 1.5 * iqr
lb = q1 - 1.5* iqr
data[(data["value"]>ub) | (data["value"]<lb)]

   value
8    400

In [11]:
data1 = data.copy()

In [12]:
import pandas as pd

In [13]:
data = pd.read_csv(r"C:\Users\Admin\OneDrive\Desktop\ML\ML-5 Outlier Removal 16952195440.txt")
data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [14]:
q1,q3 = np.percentile(data["price"],[25,75])
q1,q3

(np.float64(50.0), np.float64(120.0))

In [15]:
iqr = q3-q1
iqr

np.float64(70.0)

In [16]:
ub = q3 + 1.5 * iqr
lb = q1 - 1.5 * iqr
ub,lb

(np.float64(225.0), np.float64(-55.0))

In [17]:
data[(data["price"]>ub) | (data["price"]<lb)]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
7,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300,4.0,NaN,600.0
9,Plot Area,Ready To Move,Gandhi Bazar,6 Bedroom,NaN,1020,6.0,NaN,370.0
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785,5.0,3.0,295.0
18,Super built-up Area,Ready To Move,Ramakrishnappa Layout,3 BHK,PeBayle,2770,4.0,2.0,290.0
22,Plot Area,Ready To Move,Thanisandra,4 Bedroom,Soitya,2800,5.0,2.0,380.0
...,...,...,...,...,...,...,...,...,...
13306,Plot Area,Ready To Move,Rajarajeshwari Nagara,4 Bedroom,NaN,1200,5.0,NaN,325.0
13311,Plot Area,Ready To Move,Ramamurthy Nagar,7 Bedroom,NaN,1500,9.0,2.0,250.0
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.0
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.0

In [18]:
data.isnull().mean()*100

area_type        0.000000
availability     0.000000
location         0.007508
size             0.120120
society         41.306306
total_sqft       0.000000
bath             0.548048
balcony          4.572072
price            0.000000
dtype: float64